name: Build and Deploy to Docker Hub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build docker image
        run: |
          docker build ./Beverage_DB -t huyplt22/demo-ci-cd-gitlab:latest 
          docker build ./Beverage_DW -t huyplt22/demo-ci-cd-gitlab:latest
      - name: push docker image
        run: |
          docker login -u ${{ secrets.huyplt22 }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push huyplt22/demo-ci-cd-gitlab:latest