name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi pull request vào nhánh main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Checkout mã nguồn của repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      run: 
        docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_NAME }}/BeverageDB:latest 
        docker build -t ${{ secrets.DOCKER_NAME }}/BeverageDW:latest .

    # Push Docker image lên Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_NAME }}/demo-ci-cd-gitlab:latest
